---
title: "Load integrate h5ads"
output: html_document
date: "2024-11-07"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Prereqs

Paths and libraries
```{r}
library(Seurat)
library(tidyverse)
library(gridExtra)

#https://github.com/cellgeni/schard
#devtools::install_github("cellgeni/schard")

library(schard)

#install.packages('devtools')
#devtools::install_github('immunogenomics/presto')
library(presto)

indir <- "/sbgenomics/project-files"
outdir <- "/sbgenomics/output-files"


```

# Load h5ads

```{r}
tregfiles <- list.files(indir, pattern = "tregs_v2.h5ad")
fnames <- file.path(indir, tregfiles)
fnames.base <- basename(fnames) %>%
  gsub(".h5ad","",.)

fnames

obj.list <- fnames %>%
  purrr::map(~schard::h5ad2seurat(.x))

names(obj.list) <- fnames.base
obj.list

```

# Standardize feature names

```{r}
# Check that all features are gene symbols
obj.list %>%
  purrr::map(~Features(.x)[1:10])

# There are multiple features that point to the same symbol, so 
#  these counts must be aggregated
#feats <- rownames(obj.list[[1]])
#feats[str_detect(feats, "[.]")]

# function to aggregate counts from duplicate gene symbols
#obj1 <- obj.list[[1]]
aggregate_symbs <- function(obj1){
  
  # Extract the expression matrix from the RNA assay
  rna_data <- obj1@assays$RNA@data
  rownames(rna_data)[1:10] # features

  
  # Remove suffixes like .1, .2 from feature names
  # Update the matrix rownames
  newnames <- gsub("\\.[0-9]+$", "", rownames(rna_data))
  #newnames[str_detect(newnames, "[.]")]
  #newnames[grepl("CTD-2192J16",newnames)]
  rownames(rna_data) <- newnames
  
  # Transpose the data to make features the columns and cells the rows
  rna_data_t <- t(rna_data)
  
  # Create a data frame and aggregate the duplicate feature names (columns now)
  aggregated_data <- as.data.frame(rna_data_t)
  aggregated_data$CellName <- rownames(aggregated_data)
  
  # Aggregate by feature name, summing the expression values for duplicates
  aggregated_data <- aggregate(. ~ CellName, data = aggregated_data, FUN = sum)
  
  ncol(aggregated_data) # features after aggregation
  ncol(rna_data_t) # features before aggregation
  
  # The result of aggregate will have the feature names in the first column, so set the row names
  rownames(aggregated_data) <- aggregated_data$CellName
  # Remove the redundant 'CellName' column
  aggregated_data <- aggregated_data[, -1]
  
  # Create a fresh Seurat object
  # extract metadata
  md <- obj1@meta.data %>%
    rownames_to_column(var = "cellid") %>%
    data.frame() 
  rownames(md) <- md$cellid
  # re-order cells in count matrix
  aggregated_data.o <- aggregated_data[md$cellid,]
  #rownames(aggregated_data.o)[1:10]
  #rownames(md)[1:10]
  
  obj1.agg <- CreateSeuratObject(counts = t(aggregated_data.o), project = "SeuratProject", assay = "RNA",
                     min.cells = 0, min.features = 0, names.field = 1,
                     names.delim = "_", meta.data = md)
  
  
  return(obj1.agg)
  
}

intermedb <- "obj-list-agg.RDS"
if(!file.exists(file.path(indir, intermedb))){
  
  obj.list.agg <- obj.list %>%
    purrr::map(~aggregate_symbs(.x))
  # started 11:01, ended ...11:31
  saveRDS(obj.list.agg, file = file.path(outdir, intermedb))
  
}else{
  obj.list.agg <- readRDS(file.path(indir, intermedb))
}

tab.agg <- obj.list.agg %>%
  purrr::map(~length(Features(.x))) %>%
  purrr::map_dfr(~data.frame(n.features = .x), .id = "fname.base") %>%
  mutate(symbs.aggr = T)

tab.orig <- obj.list %>%
  purrr::map(~length(Features(.x))) %>%
  purrr::map_dfr(~data.frame(n.features = .x), .id = "fname.base")%>%
  mutate(symbs.aggr = F)

tab.agg %>%
  full_join(tab.orig) %>%
  pivot_wider(id_cols = c(fname.base),
              names_from = symbs.aggr,
              values_from = n.features)

```

# Merge Tregs into 1 object

```{r}
intermedb <- "obj.RDS"
if(!file.exists(file.path(indir, intermedb))){
  
  # add name of each h5ad source file to metadata
  for(i in 1:length(obj.list.agg)){
    obj.list.agg[[i]]$sourcefile <- names(obj.list.agg)[i]
  }
  
  # merge into 1 seurat object
  merged_seurat <- merge(obj.list.agg[[1]], y = c(obj.list.agg[[2]],
                                                  obj.list.agg[[3]],
                                                  obj.list.agg[[4]],
                                                  obj.list.agg[[5]],
                                                  obj.list.agg[[6]],
                                                  obj.list.agg[[7]]))
  
  # summarize the number of cells from each sourcefile
  merged_seurat@meta.data %>%
    group_by(sourcefile) %>%
    summarize(n = n())
  
  # Make sure each sourcefile is a Layer
  #Layers(merged_seurat)
  
  obj <- merged_seurat
  obj <- NormalizeData(obj)
  obj <- FindVariableFeatures(obj)
  obj <- ScaleData(obj)
  obj <- RunPCA(obj)
  
  # generate un-integrated umap
  obj <- FindNeighbors(obj, dims = 1:30, reduction = "pca")
  obj <- FindClusters(obj, resolution = 0.2, cluster.name = "unintegrated_clusters")
  obj <- RunUMAP(obj, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")
  
  intermedb
  saveRDS(obj, file = file.path(outdir, intermedb))
  
}else{
  obj <- readRDS(file.path(indir, intermedb))
}

#dir(outdir)

DimPlot(
  obj,
  reduction = "umap.unintegrated",
  group.by = c("sourcefile"), 
  label.size = 2
)

DimPlot(
  obj,
  reduction = "umap.unintegrated",
  group.by = c("unintegrated_clusters"),
  label.size = 2
)

```

# Integrate with CCAIntegration
```{r}
intermedb <- "obj-int.RDS"
if(!file.exists(file.path(indir, intermedb))){
  
  # Integrate layers
  obj.int <- IntegrateLayers(
    object = obj, method = CCAIntegration,
    orig.reduction = "pca", new.reduction = "integrated.cca",
    verbose = FALSE,
    k.weight = 20
  )
  # Error: k.weight (100) is set larger than the number of cells in the smallest object (35). Please choose a smaller k.weight.
  # --> reduced to 20
  # Warning in irlba(A = mat3, nv = num.cc) : You're computing too large a percentage of total singular values, use a standard svd instead.
  
  obj.int <- FindNeighbors(obj.int, reduction = "integrated.cca", dims = 1:30)
  obj.int <- FindClusters(obj.int, resolution = 0.2, cluster.name = "cca_clusters")
  obj.int <- RunUMAP(obj.int, reduction = "integrated.cca", dims = 1:30, reduction.name = "umap.cca")
  
  intermedb
  saveRDS(obj.int, file = file.path(outdir, intermedb))
  
}else{
  obj.int <- readRDS(file.path(indir, intermedb))
}

DimPlot(
  obj.int,
  reduction = "umap.cca",
  group.by = c("sourcefile"), 
  label.size = 2
)

DimPlot(
  obj.int,
  reduction = "umap.cca",
  group.by = c("cca_clusters"),
  label.size = 2
)


```

# Integrate with Harmony -- updated to res 0.3!
```{r}
intermedb <- "obj-hint.RDS"
if(!file.exists(file.path(indir, intermedb))){
  
  # Integrate layers
  obj.hint <- IntegrateLayers(
    object = obj, method = HarmonyIntegration,
    orig.reduction = "pca", new.reduction = "harmony",
    verbose = FALSE
  )
  # initialized install of "harmony"
  obj.hint
  
  obj.hint <- FindNeighbors(obj.hint, reduction = "harmony", dims = 1:30)
  obj.hint <- FindClusters(obj.hint, resolution = 0.3, cluster.name = "harmony_clusters")
  obj.hint <- RunUMAP(obj.hint, reduction = "harmony", dims = 1:30, reduction.name = "umap.harmony")
  
  intermedb
  saveRDS(obj.hint, file = file.path(outdir, intermedb))
  
}else{
  obj.hint <- readRDS(file.path(indir, intermedb))
}


DimPlot(
  obj.hint,
  reduction = "umap.harmony",
  group.by = c("sourcefile"),
  combine = FALSE, label.size = 2
)
ggsave(filename = file.path("umap-harmony-files-res03.png"),
       width = 12,
       height = 8)

DimPlot(
  obj.hint,
  reduction = "umap.harmony",
  group.by = c("harmony_clusters"),
  combine = FALSE, label.size = 2
)
ggsave(filename = file.path("umap-harmony-clusters-res03.png"),
       width = 12,
       height = 8)


```

# Find markers (Harmony integration) using res 0.3

```{r}
obj.hint.j <- JoinLayers(obj.hint)
h.markers <- FindAllMarkers(obj.hint.j, assay = "RNA", only.pos = T)

#h.markers %>%
#    group_by(harmony_clusters) %>%
#    dplyr::filter(avg_log2FC > 1)

#VlnPlot(obj.hint, features = c("CD4", "FOXP3"))

h.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10

write.csv(top10, file.path(outdir, "top10_harmony_res03.csv"))

DoHeatmap(obj.hint, features = top10$gene) + NoLegend()
ggsave(filename = file.path("heatmap-harmony-clusters-res03.png"),
       width = 12,
       height = 8)

```

Investigate marker genes
```{r}
markertab <- readxl::read_xlsx(file.path("Other_markers.xlsx"))

activation.genes <- markertab$Activation
DotPlot(object = obj.hint.j, features = activation.genes) +
  coord_flip() +
  ggtitle("Activation")
# The following requested variables were not found: MEOX
ggsave(filename = file.path("activation-harmony-clusters-res03.png"),
       width = 12,
       height = 8)

integrin.genes <- markertab$Integrin
DotPlot(object = obj.hint.j, features = integrin.genes) +
  coord_flip() +
  ggtitle("Integrin")
# The following requested variables were not found: FAK
ggsave(filename = file.path("integrin-harmony-clusters-res03.png"),
       width = 12,
       height = 8)

```
